use swiggy;
select * from restaurants; 

-- 1. List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine
select cuisine, sum(revenue)  from 
(select * from (select cuisine, cost*rating_count as "revenue" , row_number() over(partition by cuisine order by cost*rating_count desc) as "rank" from restaurants) t 
where t.rank < 6 ) t2 
group by cuisine
order by sum(revenue) desc 
;

-- 2. What is the total revenue  generated by top 1% restaurants
select sum(revenue) from 
(select name, cost*rating_count as "revenue", row_number() over(order by cost*rating_count desc) as "rank" from restaurants) t
where t.rank <= (select count(*) from restaurants) / 100;

-- 3. Check the same for top 20% restaurants

select sum(revenue) from 
(select name, cost*rating_count as "revenue", row_number() over(order by cost*rating_count desc) as "rank" from restaurants) t
where t.rank <= ((select count(*) from restaurants)* 20) / 100;

-- 4. What % of revenue is generated by top 20% of restaurants with respect to total revenue?
with 
q1 as 
(select sum(revenue) as "20_revenue" from 
(select name, cost*rating_count as "revenue", row_number() over(order by cost*rating_count desc) as "rank" from restaurants) t
where t.rank <= ((select count(*) from restaurants)* 20) / 100) ,
q2 as 
(select sum(cost*rating_count) as "total_revenue" from restaurants)

select (20_revenue / total_revenue)*100 as "percent" from q1,q2
;


-- 5. What % of revenue is generated by top 1% of restaurants with respect to total revenue?


with 
q1 as 
(select sum(revenue) as "1_revenue" from 
(select name, cost*rating_count as "revenue", row_number() over(order by cost*rating_count desc) as "rank" from restaurants) t
where t.rank <= ((select count(*) from restaurants)*1) / 100) ,
q2 as 
(select sum(cost*rating_count) as "total_revenue" from restaurants)

select (1_revenue / total_revenue)*100 as "percent" from q1,q2
;

-- 6. find the revenue generated by top 10 restaurants as per revenue for each city?

select city, sum(rating_count * cost) as 'revenue' from (
		select * , row_number()
			over(partition by city order by cost*rating_count desc) as 'ranking'
				from restaurants) as t1
						where ranking <=10
							group by city
								order by revenue desc ;